sudo: required # hey travis we need super user permission
services:
  - docker # hey travis we need copy of docker

before_install: # all steps required before running our test on travis
  - docker build -t 361458/docker-react -f Dockerfile.dev . # before run my test, build docker dev

script: # all commands need to be excuted to run our test suite
  - docker run -e CI=true 361458/docker-react npm run test
